Devnet Docs
PowerLoom/docs pull request #18
Opened 2024-03-10 16:05 UTC by thecoderpanda

Fixes #

### Checklist
- [x] My branch is up-to-date with upstream/main branch.
- [x] Everything works and tested for major version of Python/NodeJS/Go and above.
- [x] I ran pre-commit checks against my changes.

### Current behaviour

### New expected behaviour

### Change logs

#### Added
Getting Started with Devnet
Troubleshooting Guide
Health Check

2024-03-11 08:49 UTC, muku314115 commented on docs/build-with-powerloom/snapshotter-node/lite-node/getting-started.md
> + Please do not use your NFT minting wallet to run the snapshotter lite node.The safest approach The safest approach is to generate and assign a burner wallet. You can generate a burner wallet through
"The safest approach" is repeated

2024-03-11 08:52 UTC, muku314115 commented on docs/build-with-powerloom/snapshotter-node/lite-node/getting-started.md
> + Please do not use your NFT minting wallet to run the snapshotter lite node.The safest approach The safest approach is to generate and assign a burner wallet. You can generate a burner wallet through
"The safest approach" is repeated

2024-03-14 17:21 UTC, xadahiya requested changes
Mostly looks good, added some comments for improvement!

2024-03-14 17:21 UTC, xadahiya commented on docs/build-with-powerloom/devnet/getting-started.md
> +We offer two types of Protocol State Contracts, each tailored to different Epoch Sizes, to cater to the unique complexities of your application:
A lot of lines seem very GPT like tbh, better to keep it to the point. For example -
```
Currently, there are two variations of Protocol State Contracts available. One where [Epoch]<link to epoch explanation from docs> size is set to 1 and other where epoch size is set to 10 blocks.  This should allow developers to build and experiment with a variety of use cases. If you have any custom needs, reach out to the team <link>
```
Just a quick draft but you should get the idea.

2024-03-14 17:21 UTC, xadahiya commented on docs/build-with-powerloom/devnet/getting-started.md
> +   - Epoch Size 10 Contract: `0x5B1f374C7680B310CD68351B8e9e6BeD34d8884f`
These addresses are bound to change over time, let's not keep these here.

2024-03-14 17:21 UTC, xadahiya commented on docs/build-with-powerloom/devnet/getting-started.md
> +   - `PROST_CHAIN_ID`: For Devnet, it's `104`.
Let's avoid using any values, if necessary, point them too `env.example` file

2024-03-14 17:21 UTC, xadahiya commented on docs/build-with-powerloom/devnet/health-tracking.md
> +# Health Tracking
Aren't these instructions exactly the same as Snapshotter Node health tracking? If yes, we should either link to those or reorganize the content hierarchy to better suit our needs. 
Don't think it is a good idea to repeat content.

2024-03-14 17:21 UTC, xadahiya commented on docs/build-with-powerloom/devnet/troubleshooting.md
> +
All these points are present in snapshotter node troubleshooting I think. We should just link to those and add devnet specific things here like issue with minting, burner wallet, how to check your submissions, etc.

2024-03-14 17:21 UTC, xadahiya commented on docs/participate/devnet.md
> +3. Explore the Powerloom documentation to familiarize yourself with our APIs, data models, and best practices.
Not sure if we should write this. Our focus is not on APIs or data models, this should talk about snapshotter nodes, consensus, etc.

2024-03-14 17:21 UTC, xadahiya commented on docs/participate/devnet.md
> +1. **Data Dashboards**: Create interactive visualizations and dashboards that provide insights into blockchain metrics, token economies, user behavior, and more. Empower users with data-driven decisi
Let's only write things that users can build today. We can expand later. 
Better to keep it simple and to the point IMO.

2024-03-14 17:21 UTC, xadahiya commented on docs/participate/devnet.md
> +- **Comprehensive Datasets**: Powerloom provides access to rich and diverse data markets. This allows you to work with real-world data and test your applications under realistic conditions.
```Powerloom provides access to rich and diverse data markets```
Not on devnet

2024-03-14 17:21 UTC, xadahiya commented on docs/participate/devnet.md
> +Devnet enables you to efficiently customize and analyze blockchain data to power your applications. Whether you're building a simple prototype or a complex applications, Devnet makes the development
We should rewrite this IMO. 
```
Whether you're building a simple prototype or a complex applications, Devnet makes the development process smooth and straightforward.
```
How does it make the process smooth and straightforward?

2024-04-05 15:33 UTC, closed without merging