Chore/uniswapv3 docs
PowerLoom/docs pull request #7
Opened 2024-01-15 11:12 UTC by thecoderpanda

@getjiggy UniswapV3 documentation added.

2024-01-16 20:12 UTC, SwaroopH requested changes
Left comments

2024-01-16 20:12 UTC, SwaroopH commented on docs/build-with-powerloom/use-cases/existing-implementations/uniswapv3-dashboard/category.json
> +      "description": "UniswapV3 Dashboard Implementation using Powerloom protocol"
P should be capital in protocol

2024-01-16 20:12 UTC, SwaroopH commented on docs/build-with-powerloom/use-cases/existing-implementations/uniswapv3-dashboard/index.md
> +In order to calculate our Total Value Locked data point, we must retreive every populated tick in a given pool. We accomplish this by batching RPC state overload calls to a modified [1inch UniV3Helpe
@anomit this should be on powerloom namespace ideally? We can come up with a utils or better repo name while we are at it.

2024-01-16 21:11 UTC, getjiggy commented on docs/build-with-powerloom/use-cases/existing-implementations/uniswapv3-dashboard/category.json
> +      "description": "UniswapV3 Dashboard Implementation using Powerloom protocol"
pushed update

2024-01-16 22:36 UTC, SwaroopH commented on docs/build-with-powerloom/use-cases/existing-implementations/uniswapv3-dashboard/index.md
> +In order to calculate our Total Value Locked data point, we must retreive every populated tick in a given pool. We accomplish this by batching RPC state overload calls to a modified [1inch UniV3Helpe
@getjiggy let's use this: https://github.com/PowerLoom/evm-helpers/tree/pooler

2024-01-17 06:49 UTC, SwaroopH approved these changes
LGTM

2024-04-09 05:02 UTC, closed without merging